# Generated by Django 5.2.8 on 2025-12-05 18:49

import django.db.models.deletion
import gallery.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=gallery.utils.gallery_image_path)),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('screenshot', 'Скріншот'), ('video', 'Відео'), ('other', 'Інше'), ('unknown', 'Не вказано')], default='unknown', max_length=20)),
                ('game_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медіафайл',
                'verbose_name_plural': 'Медіафайли',
            },
        ),
    ]
