# Generated by Django 5.2.8 on 2025-11-29 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at'], 'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.AddField(
            model_name='material',
            name='engine',
            field=models.CharField(choices=[('pygame', 'Pygame'), ('renpy', "Ren'Py"), ('unity', 'Unity'), ('unreal', 'Unreal Engine'), ('godot', 'Godot'), ('gamemaker', 'GameMaker'), ('construct', 'Construct 3'), ('custom', 'Власний рушій / Без рушія'), ('other', 'Інше')], default=None, max_length=64, verbose_name='Рушій'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_published',
            field=models.CharField(choices=[('published', 'Опубліковано'), ('not_published', 'Не опубліковано')], default='published', max_length=20, verbose_name='Статус публікації'),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default=None, max_length=128, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('file', 'Файл'), ('link', 'Посилання'), ('video', 'Відео')], max_length=16, verbose_name='Тип файлу'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materials.materialcategory', verbose_name='Категорія'),
            preserve_default=False,
        ),
    ]
