# Generated by Django 5.2.8 on 2025-11-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('role', models.CharField(choices=[('User', 'User'), ('Student', 'Student'), ('Moderator', 'Mod'), ('Admin', 'Admin')], default='User')),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
