# Generated by Django 5.2.8 on 2025-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.TextField(blank=True, default='No Description Provided', max_length=5000, null=True),
        ),
    ]
