# Generated by Django 5.2.8 on 2025-11-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_options_usermodel_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(max_length=20)),
                ('about', models.TextField(blank=True, default='No Description Provided', max_length=5000, null=True)),
                ('role', models.CharField(choices=[('User', 'User'), ('Student', 'Student'), ('Moderator', 'Mod'), ('Admin', 'Admin')], default='User')),
                ('favourite_game', models.TextField(default='None', max_length=50)),
                ('github_link', models.URLField(max_length=500, null=True)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('favourite_genres', models.ManyToManyField(null=True, to='accounts.genreitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
